apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-app-backend
  namespace: garage-app
  labels:
    app: garage
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ycr-secret
      containers:
        - name: backend
          image: cr.yandex/crp73fh09ihdevr61ugo/garage-backend:46ab3b4e2b9f9e4d0a61f0a73913097d5b696332
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/garage
            - name: SPRING_DATASOURCE_USERNAME
              value: garage
            - name: SPRING_DATASOURCE_PASSWORD
              value: garage
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "320Mi"
              ephemeral-storage: "128Mi"
            limits:
              cpu: "1000m"
              memory: "768Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 6
