apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-app-frontend
  namespace: garage-app
  labels:
    app: garage
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cr.yandex/crp73fh09ihdevr61ugo/garage-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
