apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-app-frontend
  namespace: garage-app
  labels:
    app: garage
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ycr-secret
      containers:
        - name: frontend
          image: cr.yandex/crp73fh09ihdevr61ugo/garage-frontend:3a95e95b2b4c2281e02359b8c294d898e201d97f
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
